### ISSUE TITLE
Sorting out a large log file with lots of errors and warnings. It mentioned Alloyed.

### ISSUE THREAD

**Issue by DigitalWendigo** [MythrilBagels/Create-Alloyed#26]
Hello, I'm sorry to bother you. 
I'm trying to figure out what all this means in the log file. 
I'm going through every warning and error and sort it by mod name and it mentioned Alloyed. 
Would you be so kind as to help me figure out what these warnings mean? Can I safely ignore the Alloyed warnings in this log file or are they part of an actual issue?
Please and thank you. 

https://gist.github.com/DigitalWendigo/1a0d570a2ed16b4c291d3fe9d417745e

**Comment by FortressNebula** [comment]
Most of the warnings are totally fine, thats the Create: Deco compat blocks. So Forge is just complaining about them having weird blockstates since Create: Deco isn't loaded. Nothing to worry about.

The only strange one is the `alloyed:sprinkler`, since that shouldn't be in the final jar. It shouldn't cause any issues since it appears to just be a loot table, but it is odd, and we'll look into it.

**Comment by DigitalWendigo** [comment]
Ah, alright, Thanks for the quick reply and explaining. I hope you'll have a great day!
