### ISSUE TITLE
[1.18.2] Crash with newest Create/Flywheel version

### ISSUE THREAD

**Issue by Kallixer** [MythrilBagels/Create-Alloyed#45]
The game crashes on startup with Create 0.5.0.d and Flywheel 0.6.5. No other mods were enabled.

Forge version: 40.1.73

[latest.log](https://github.com/MythrilBagels/Create-Alloyed/files/9381972/latest.log)
[debug.log](https://github.com/MythrilBagels/Create-Alloyed/files/9381977/debug.log)

Thanks for your work! :)

**Comment by Quinntyx** [comment]
1000th report in the last couple days please check the closed issues before opening a new one lol
But yeah, the devs already know about and are working on this, it's not compatible with latest Create yet

Trust me I want them to update as much as anyone I've made a modpack that can't be updated to create 0.5 yet because of it

**Comment by FortressNebula** [comment]
Yep, what FlareStormGaming said.
